const vinyls = [
  {
    title: "Master of Puppets",
    artist: "Metallica",
    genre: "Thrash metal",
    label: "Elektra",
    year: 1986,
    format: "LP",
    rpm: 33,
    condition: "Muy bueno",
    stock: true,
  },
  {
    title: "The Number of the Beast",
    artist: "Iron Maiden",
    genre: "Heavy metal",
    label: "EMI",
    year: 1982,
    format: "LP",
    rpm: 33,
    condition: "Usado",
    cover:
      "https://upload.wikimedia.org/wikipedia/en/thumb/3/32/IronMaiden_NumberOfBeast.jpg/250px-IronMaiden_NumberOfBeast.jpg",
    stock: true,
  },
  {
    title: "Reign in Blood",
    artist: "Slayer",
    genre: "Thrash metal",
    label: "Def Jam",
    year: 1986,
    format: "LP",
    rpm: 33,
    condition: "Con leves daños",
    cover:
      "https://upload.wikimedia.org/wikipedia/en/thumb/8/8e/Reign_in_blood.jpg/250px-Reign_in_blood.jpg",
    stock: false,
  },
  {
    title: "British Steel",
    artist: "Judas Priest",
    genre: "Heavy metal",
    label: "Columbia",
    year: 1980,
    format: "LP",
    rpm: 33,
    condition: "Muy bueno",
    cover:
      "https://upload.wikimedia.org/wikipedia/en/thumb/9/97/Judas_Priest_British_Steel.jpg/250px-Judas_Priest_British_Steel.jpg",
    stock: true,
  },
  {
    title: "Holy Diver",
    artist: "Dio",
    genre: "Heavy metal",
    label: "Warner Bros.",
    year: 1983,
    format: "LP",
    rpm: 33,
    condition: "Nuevo",
    stock: false,
  },
  {
    title: "Blizzard of Ozz",
    artist: "Ozzy Osbourne",
    genre: "Heavy metal",
    label: "Jet",
    year: 1980,
    format: "LP",
    rpm: 33,
    condition: "Usado",
    cover:
      "https://upload.wikimedia.org/wikipedia/en/thumb/2/23/Blizzard_of_ozz.jpg/250px-Blizzard_of_ozz.jpg",
    stock: true,
  },
  {
    title: "Heaven and Hell",
    artist: "Black Sabbath",
    genre: "Heavy metal",
    label: "Vertigo",
    year: 1980,
    format: "LP",
    rpm: 33,
    condition: "Muy bueno",
    cover:
      "https://upload.wikimedia.org/wikipedia/en/thumb/f/f8/Black_Sabbath_Heaven_and_Hell.jpg/250px-Black_Sabbath_Heaven_and_Hell.jpg",
    stock: false,
  },
  {
    title: "...Baby One More Time",
    artist: "Britney Spears",
    genre: "Pop",
    label: "Jive",
    year: 1999,
    format: "LP",
    rpm: 33,
    condition: "Nuevo",
    cover:
      "https://upload.wikimedia.org/wikipedia/en/thumb/9/9a/..._Baby_One_More_Time_%28album%29.png/250px-..._Baby_One_More_Time_%28album%29.png",
    stock: true,
  },
  {
    title: "Millennium",
    artist: "Backstreet Boys",
    genre: "Pop",
    label: "Jive",
    year: 1999,
    format: "LP",
    rpm: 33,
    condition: "Muy bueno",
    stock: true,
  },
  {
    title: "Spice",
    artist: "Spice Girls",
    genre: "Pop",
    label: "Virgin",
    year: 1996,
    format: "LP",
    rpm: 33,
    condition: "Usado",
    stock: false,
  },
  {
    title: "Ray of Light",
    artist: "Madonna",
    genre: "Electronica",
    label: "Maverick",
    year: 1998,
    format: "LP",
    rpm: 33,
    condition: "Muy bueno",
    cover:
      "https://upload.wikimedia.org/wikipedia/en/thumb/d/dd/Ray_of_Light_Madonna.png/250px-Ray_of_Light_Madonna.png",
    stock: true,
  },
  {
    title: "CrazySexyCool",
    artist: "TLC",
    genre: "R&B",
    label: "LaFace",
    year: 1994,
    format: "LP",
    rpm: 33,
    condition: "Con leves daños",
    stock: true,
  },
  {
    title: "The Velvet Rope",
    artist: "Janet Jackson",
    genre: "R&B",
    label: "Virgin",
    year: 1997,
    format: "LP",
    rpm: 33,
    condition: "Muy bueno",
    stock: false,
  },
  {
    title: "Let's Talk About Love",
    artist: "Celine Dion",
    genre: "Pop",
    label: "Columbia",
    year: 1997,
    format: "LP",
    rpm: 33,
    condition: "Nuevo",
    cover:
      "https://upload.wikimedia.org/wikipedia/en/thumb/4/48/Lets_talk_about_love.jpg/250px-Lets_talk_about_love.jpg",
    stock: true,
  },
  {
    title: "Aquarium",
    artist: "Aqua",
    genre: "Eurodance",
    year: 1997,
    format: "LP",
    rpm: 33,
    condition: "Usado",
    cover:
      "https://upload.wikimedia.org/wikipedia/en/thumb/8/80/Aquariumcover.jpg/250px-Aquariumcover.jpg",
    stock: false,
  },
  {
    title: "Rumours",
    artist: "Fleetwood Mac",
    genre: "Pop rock",
    label: "Warner Bros.",
    year: 1977,
    format: "LP",
    rpm: 33,
    condition: "Muy bueno",
    stock: true,
  },
  {
    title: "Thriller",
    artist: "Michael Jackson",
    genre: "Pop",
    label: "Epic",
    year: 1982,
    format: "LP",
    rpm: 33,
    condition: "Nuevo",
    cover:
      "https://upload.wikimedia.org/wikipedia/en/thumb/5/55/Michael_Jackson_-_Thriller.png/250px-Michael_Jackson_-_Thriller.png",
    stock: true,
  },
  {
    title: "Discovery",
    artist: "Daft Punk",
    genre: "French house",
    label: "Virgin",
    year: 2001,
    format: "LP",
    rpm: 33,
    condition: "Muy bueno",
    cover:
      "https://upload.wikimedia.org/wikipedia/en/thumb/2/27/Daft_Punk_-_Discovery.png/250px-Daft_Punk_-_Discovery.png",
    stock: false,
  },
  {
    title: "Kind of Blue",
    artist: "Miles Davis",
    genre: "Modal jazz",
    label: "Columbia",
    year: 1959,
    format: "LP",
    rpm: 33,
    condition: "Usado",
    cover:
      "https://upload.wikimedia.org/wikipedia/en/thumb/1/10/Miles_Davis_-_Kind_of_Blue_album_cover.jpg/250px-Miles_Davis_-_Kind_of_Blue_album_cover.jpg",
    stock: true,
  },
  {
    title: "Nevermind",
    artist: "Nirvana",
    genre: "Grunge",
    label: "DGC",
    year: 1991,
    format: "LP",
    rpm: 33,
    condition: "Con leves daños",
    cover:
      "https://upload.wikimedia.org/wikipedia/en/thumb/b/b7/NirvanaNevermindalbumcover.jpg/250px-NirvanaNevermindalbumcover.jpg",
    stock: false,
  },
];
